# Generated by Django 2.0.5 on 2018-05-05 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0004_auto_20180505_2253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='summary',
            field=models.CharField(max_length=200),
        ),
    ]
