# Generated by Django 2.0.5 on 2018-05-05 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0005_auto_20180505_2310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='description',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='article',
            name='document',
            field=models.URLField(blank=True, default='', max_length=1000),
        ),
    ]
